@extends('layouts.app')

@section('title', 'لوحة التحكم | منصة ردود')

@section('styles')
<!-- Styles are now mostly handled by theme.blade.php -->
<style>
  /* حل مشكلة اختفاء النصوص داخل الشارات (Badges) */
  .badge-auto {
    background-color: var(--gold) !important;
    color: var(--bg-dark) !important;
    font-weight: 700 !important;
    padding: 6px 14px !important;
    border-radius: 50px !important;
    font-size: 0.8rem !important;
    display: inline-block !important;
  }

  .badge-human {
    background-color: #0ea5e9 !important;
    color: #000000 !important;
    font-weight: 700 !important;
    padding: 6px 14px !important;
    border-radius: 50px !important;
    font-size: 0.8rem !important;
    display: inline-block !important;
  }

  /* شارة حالة البوت بالعلوي */
  .status-badge {
    background: rgba(46, 204, 113, 0.15) !important;
    color: #2ecc71 !important;
    border: 1px solid #2ecc71;
    padding: 8px 16px;
    border-radius: 50px;
    font-size: 0.85rem;
    font-weight: 600;
  }
</style>
@endsection

@section('content')
<!-- الشريط العلوي -->
<div class="d-flex justify-content-between align-items-center mb-4 pb-3 border-bottom border-secondary border-opacity-25">
  <div>
    <h3 class="fw-bold text-white mb-1">أهلاً بك، {{ auth()->user()->name ?? 'متجر الأمجاد' }} 👋</h3>
    <p class="text-white-50 mb-0 fs-7">إليك ملخص أداء مساعدك الذكي لهذا اليوم</p>
  </div>
  <div>
    <span class="status-badge">
      <i class="bi bi-circle-fill me-1 fs-9"></i> البوت متصل الآن
    </span>
  </div>
</div>

<!-- Section: Conversion Analytics & ROI Tracking Ribbon -->
<div class="mb-4">
  <div class="d-flex justify-content-between align-items-center mb-3">
    <div>
      <h5 class="fw-bold text-white mb-0 d-flex align-items-center gap-2">
        <i class="bi bi-graph-up-arrow text-gold"></i>
        <span>العائد المالي على الاستثمار ومبيعات الذكاء الاصطناعي (Conversion & ROI Analytics)</span>
      </h5>
      <small class="text-white-50">تتبع مبيعات المتجر المحققة عبر المحادثات وتوفير ساعات العمل التشغيلية</small>
    </div>
    <div class="d-flex gap-1" id="roiTimeFilter">
      <span class="badge bg-gold text-dark fs-9 fw-bold px-3 py-1 d-flex align-items-center gap-1">
        <i class="bi bi-check2-circle"></i> مؤشرات العائد النشطة
      </span>
    </div>
  </div>

  <div class="row g-3">
    <!-- 1. Revenue Generated by Rudood -->
    <div class="col-md-3">
      <div class="stat-card p-3 border border-gold border-opacity-30 position-relative overflow-hidden" style="background: linear-gradient(145deg, rgba(212,175,55,0.08) 0%, rgba(15,23,42,0.9) 100%);">
        <div class="d-flex justify-content-between align-items-start mb-2">
          <span class="text-white-50 fs-8">الإيرادات المحققة بواسطة ردود</span>
          <span class="badge badge-roi-gold rounded-pill px-2.5 py-1 fs-9 fw-bold"><i class="bi bi-arrow-up-right me-1"></i>+24.5%</span>
        </div>
        <h3 class="fw-bold text-gold mb-1" id="roiRevenueVal">{{ number_format($roi_stats['revenue_generated'] ?? 0, 2) }} <span class="fs-8 text-white-50">ر.س</span></h3>
        <small class="text-white-50 fs-9 d-block">مبيعات مكتملة ناتجة عن محادثات AI</small>
      </div>
    </div>

    <!-- 2. Bot Deflection Rate -->
    <div class="col-md-3">
      <div class="stat-card p-3 border border-success border-opacity-30" style="background: linear-gradient(145deg, rgba(34,197,94,0.08) 0%, rgba(15,23,42,0.9) 100%);">
        <div class="d-flex justify-content-between align-items-start mb-2">
          <span class="text-white-50 fs-8">معدل تجنيب الموظفين (Deflection)</span>
          <span class="badge badge-roi-success rounded-pill px-2.5 py-1 fs-9">آلي بالكامل</span>
        </div>
        <h3 class="fw-bold text-success mb-1" id="roiDeflectionVal">{{ $roi_stats['deflection_rate'] ?? 0 }}%</h3>
        <small class="text-white-50 fs-9 d-block">{{ $roi_stats['bot_resolved'] ?? 0 }} استفسار حُل دون تدخل بشري</small>
      </div>
    </div>

    <!-- 3. Hours Saved -->
    <div class="col-md-3">
      <div class="stat-card p-3 border border-info border-opacity-30" style="background: linear-gradient(145deg, rgba(14,165,233,0.08) 0%, rgba(15,23,42,0.9) 100%);">
        <div class="d-flex justify-content-between align-items-start mb-2">
          <span class="text-white-50 fs-8">ساعات عمل الموظفين الموفرة</span>
          <span class="badge badge-roi-info rounded-pill px-2.5 py-1 fs-9">وفر تشغيلي</span>
        </div>
        <h3 class="fw-bold text-info mb-1" id="roiHoursVal">{{ $roi_stats['hours_saved'] ?? 0 }} <span class="fs-8 text-white-50">ساعة</span></h3>
        <small class="text-white-50 fs-9 d-block">توفير تكلفة قدره ~{{ number_format($roi_stats['cost_savings_amount'] ?? 0) }} ر.س</small>
      </div>
    </div>

    <!-- 4. Attributed Orders -->
    <div class="col-md-3">
      <div class="stat-card p-3 border border-warning border-opacity-30" style="background: linear-gradient(145deg, rgba(245,158,11,0.08) 0%, rgba(15,23,42,0.9) 100%);">
        <div class="d-flex justify-content-between align-items-start mb-2">
          <span class="text-white-50 fs-8">طلبات الشراء المحولة</span>
          <span class="badge badge-roi-warning rounded-pill px-2.5 py-1 fs-9">تحويل {{ $roi_stats['conversion_rate'] ?? 0 }}%</span>
        </div>
        <h3 class="fw-bold text-white mb-1" id="roiOrdersVal">{{ $roi_stats['converted_orders_count'] ?? 0 }} <span class="fs-8 text-white-50">طلب</span></h3>
        <small class="text-white-50 fs-9 d-block">متوسط قيمة الطلب: {{ number_format($roi_stats['average_order_value'] ?? 0) }} ر.س</small>
      </div>
    </div>
  </div>
</div>

<!-- Row 1: كروت الإحصائيات (Primary KPIs) -->
<div class="row g-4 mb-4">
  <div class="col-md-3">
    <div class="stat-card d-flex align-items-center gap-3">
      <div class="icon-box-dash"><i class="bi bi-chat-left-text-fill"></i></div>
      <div>
        <span class="text-white-50 d-block fs-7">إجمالي المحادثات</span>
        <h3 class="fw-bold text-white mb-0">{{ $stats['total_conversations'] ?? '0' }}</h3>
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="stat-card d-flex align-items-center gap-3">
      <div class="icon-box-dash"><i class="bi bi-robot"></i></div>
      <div>
        <span class="text-white-50 d-block fs-7">ردود الذكاء الاصطناعي</span>
        <h3 class="fw-bold text-white mb-0">{{ $stats['resolution_rate'] ?? '0%' }}</h3>
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="stat-card d-flex align-items-center gap-3">
      <div class="icon-box-dash"><i class="bi bi-people-fill"></i></div>
      <div>
        <span class="text-white-50 d-block fs-7">العملاء النشطون</span>
        <h3 class="fw-bold text-white mb-0">{{ $stats['new_inquiries'] ?? '0' }}</h3>
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="stat-card d-flex align-items-center gap-3">
      <div class="icon-box-dash"><i class="bi bi-clock-history"></i></div>
      <div>
        <span class="text-white-50 d-block fs-7">متوسط سرعة الرد</span>
        <h3 class="fw-bold text-white mb-0">{{ $stats['avg_response_time'] ?? '—' }}</h3>
      </div>
    </div>
  </div>
</div>

<!-- Row 2: Secondary Cards -->
<div class="row g-4 mb-4">
  <div class="col-md-3">
    <div class="stat-card d-flex align-items-center gap-3">
      <div class="icon-box-dash"><i class="bi bi-cpu"></i></div>
      <div>
        <span class="text-white-50 d-block fs-7">البوتات النشطة</span>
        <h3 class="fw-bold text-white mb-0">{{ $secondary_stats['active_bots'] ?? '0' }}</h3>
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="stat-card d-flex align-items-center gap-3">
      <div class="icon-box-dash"><i class="bi bi-person-badge"></i></div>
      <div>
        <span class="text-white-50 d-block fs-7">مستخدمو الفريق</span>
        <h3 class="fw-bold text-white mb-0">{{ $secondary_stats['team_users'] ?? '0' }}</h3>
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="stat-card d-flex align-items-center gap-3">
      <div class="icon-box-dash"><i class="bi bi-file-earmark-text"></i></div>
      <div>
        <span class="text-white-50 d-block fs-7">مستندات المعرفة</span>
        <h3 class="fw-bold text-white mb-0">{{ $secondary_stats['knowledge_docs'] ?? '0' }}</h3>
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="stat-card d-flex align-items-center gap-3">
      <div class="icon-box-dash"><i class="bi bi-plug"></i></div>
      <div>
        <span class="text-white-50 d-block fs-7">القنوات المتصلة</span>
        <h3 class="fw-bold text-white mb-0">{{ $secondary_stats['connected_channels'] ?? '0' }}</h3>
      </div>
    </div>
  </div>
</div>

<!-- Row 2.5: Bot Deflection Rate Trends & Sales Attributed Conversions -->
<div class="row g-4 mb-4">
  <div class="col-md-7">
    <div class="stat-card h-100 p-4">
      <div class="d-flex justify-content-between align-items-center mb-3">
        <div>
          <h5 class="fw-bold text-white mb-1"><i class="bi bi-bar-chart-line-fill text-gold me-2"></i>اتجاهات تجنيب الموظفين وساعات العمل الموفرة</h5>
          <small class="text-white-50 fs-9">مقارنة شهرية بين التذاكر المحلولة ذاتياً بواسطة الذكاء الاصطناعي مقابل ساعات عمل الموظفين الموفرة</small>
        </div>
        <span class="badge bg-dark border border-secondary border-opacity-40 text-gold fs-9">آخر 6 أشهر</span>
      </div>
      <div id="deflectionTrendsChart" style="min-height: 280px;"></div>
    </div>
  </div>

  <div class="col-md-5">
    <div class="stat-card p-0 overflow-hidden h-100">
      <div class="p-4 border-bottom d-flex justify-content-between align-items-center" style="border-color: rgba(255,255,255,0.05) !important;">
        <div>
          <h5 class="fw-bold text-white mb-0"><i class="bi bi-cart-check-fill text-gold me-2"></i>أحدث المبيعات المحولة عبر AI</h5>
          <small class="text-white-50 fs-9">طلبات تمت بعد تفاعل مباشر مع المساعد الذكي</small>
        </div>
        <span class="badge badge-roi-success rounded-pill px-2.5 py-1 fs-9">محققة</span>
      </div>
      <div class="table-responsive">
        <table class="custom-dark-table mb-0">
          <thead>
            <tr>
              <th>الطلب</th>
              <th>العميل</th>
              <th>المصدر</th>
              <th>القيمة</th>
            </tr>
          </thead>
          <tbody>
            @forelse ($recent_conversions ?? [] as $convOrder)
            <tr>
              <td>
                <div class="fw-bold text-white fs-8">{{ $convOrder->order_number }}</div>
                <small class="text-white-50" style="font-size: 0.72rem;">{{ $convOrder->created_at ? $convOrder->created_at->format('m/d') : 'مؤخراً' }}</small>
              </td>
              <td>
                <div class="text-white fs-8">{{ $convOrder->customer_name ?? 'عميل المتجر' }}</div>
              </td>
              <td>
                @php
                  $srcLabel = match($convOrder->attribution_type) {
                    'catalog_order' => 'كتالوج تفاعلي 🛍️',
                    'product_recommendation' => 'توصية ذكية 💡',
                    'live_chat_checkout' => 'شات مباشر 💬',
                    'order_inquiry' => 'استفسار طلب 📦',
                    default => 'محادثة AI 🤖',
                  };
                @endphp
                <span class="badge bg-dark border border-secondary border-opacity-40 text-gold fs-9">{{ $srcLabel }}</span>
              </td>
              <td>
                <span class="text-gold fw-bold fs-8">{{ number_format($convOrder->total_amount, 2) }} ر.س</span>
              </td>
            </tr>
            @empty
            <tr>
              <td colspan="4" class="text-center py-4 text-white-50">لا توجد طلبات محولة بعد</td>
            </tr>
            @endforelse
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<!-- Row 3: Charts -->
<div class="row g-4 mb-4">
  <div class="col-md-8">
    <div class="stat-card h-100 p-4">
      <h5 class="fw-bold text-white mb-4"><i class="bi bi-graph-up text-gold me-2"></i>نشاط الرسائل (آخر 7 أيام)</h5>
      <div id="messagesChart" style="min-height: 250px;"></div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="stat-card h-100 p-4">
      <h5 class="fw-bold text-white mb-4"><i class="bi bi-pie-chart text-gold me-2"></i>توزيع القنوات</h5>
      <div id="channelsChart" style="min-height: 250px;"></div>
    </div>
  </div>
</div>

<!-- Row 4: Tables -->
<div class="row g-4 mb-4">
  <!-- Recent Conversations -->
  <div class="col-md-6">
    <div class="stat-card p-0 overflow-hidden h-100">
      <div class="p-4 border-bottom" style="border-color: rgba(255,255,255,0.05) !important;">
        <h5 class="fw-bold text-white mb-0"><i class="bi bi-clock text-gold me-2"></i>آخر المحادثات</h5>
      </div>
      <table class="custom-dark-table mb-0">
        <thead>
          <tr>
            <th>العميل</th>
            <th>القناة</th>
            <th>حالة الرد</th>
            <th>الوقت</th>
          </tr>
        </thead>
        <tbody>
          @forelse ($recent_conversations ?? [] as $conv)
          <tr>
            <td class="fw-bold">{{ $conv->customer?->name ?? 'عميل جديد' }}</td>
            <td>
              @php $platform = $conv->customer?->platform ?? 'web'; @endphp
              <i class="bi bi-{{ $platform === 'whatsapp' ? 'whatsapp text-success' : ($platform === 'instagram' ? 'instagram text-danger' : 'globe text-info') }} me-1"></i>
              {{ ucfirst($platform) }}
            </td>
            <td>
              @if ($conv->status === 'human_handling')
                <span class="badge-human">محول للموظف</span>
              @else
                <span class="badge-auto">آلي</span>
              @endif
            </td>
            <td class="text-white-50 fs-7">{{ $conv->updated_at->diffForHumans() }}</td>
          </tr>
          @empty
          <tr>
            <td colspan="4" class="text-center py-4 text-white-50">لا توجد محادثات</td>
          </tr>
          @endforelse
        </tbody>
      </table>
    </div>
  </div>

  <!-- Connected Channels -->
  <div class="col-md-6">
    <div class="stat-card p-0 overflow-hidden h-100">
      <div class="p-4 border-bottom" style="border-color: rgba(255,255,255,0.05) !important;">
        <h5 class="fw-bold text-white mb-0"><i class="bi bi-link-45deg text-gold me-2"></i>حالة القنوات المتصلة</h5>
      </div>
      <table class="custom-dark-table mb-0">
        <thead>
          <tr>
            <th>القناة</th>
            <th>الحالة</th>
          </tr>
        </thead>
        <tbody>
          @forelse ($channels ?? [] as $ch)
          <tr>
            <td class="fw-bold">
              <i class="bi bi-{{ $ch->platform === 'whatsapp' ? 'whatsapp text-success' : ($ch->platform === 'instagram' ? 'instagram text-danger' : 'globe text-info') }} me-1"></i>
              {{ ucfirst($ch->platform) }}
            </td>
            <td>
              @if($ch->is_connected)
                <span class="text-success"><i class="bi bi-check-circle me-1"></i> متصل</span>
              @else
                <span class="text-danger"><i class="bi bi-x-circle me-1"></i> مفصول</span>
              @endif
            </td>
          </tr>
          @empty
          <tr>
            <td colspan="2" class="text-center py-4 text-white-50">لا توجد قنوات</td>
          </tr>
          @endforelse
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="row g-4 mb-5">
  <!-- Recent Rules -->
  <div class="col-md-6">
    <div class="stat-card p-0 overflow-hidden h-100">
      <div class="p-4 border-bottom" style="border-color: rgba(255,255,255,0.05) !important;">
        <h5 class="fw-bold text-white mb-0"><i class="bi bi-list-check text-gold me-2"></i>أحدث القواعد المضافة</h5>
      </div>
      <table class="custom-dark-table mb-0">
        <thead>
          <tr>
            <th>السؤال/الكلمة الدلالية</th>
            <th>الإجابة المخصصة</th>
          </tr>
        </thead>
        <tbody>
          @forelse ($recent_rules ?? [] as $rule)
          <tr>
            <td class="fw-bold">{{ Str::limit($rule->question ?? (is_array($rule->keywords) ? implode(', ', $rule->keywords) : 'قاعدة عامة'), 30) }}</td>
            <td class="text-white-50 fs-7">{{ Str::limit($rule->reply_template, 40) }}</td>
          </tr>
          @empty
          <tr>
            <td colspan="2" class="text-center py-4 text-white-50">لا توجد قواعد مسجلة</td>
          </tr>
          @endforelse
        </tbody>
      </table>
    </div>
  </div>

  <!-- Recent AI Decisions -->
  <div class="col-md-6">
    <div class="stat-card p-0 overflow-hidden h-100">
      <div class="p-4 border-bottom" style="border-color: rgba(255,255,255,0.05) !important;">
        <h5 class="fw-bold text-white mb-0"><i class="bi bi-cpu text-gold me-2"></i>أحدث قرارات الـ AI</h5>
      </div>
      <table class="custom-dark-table mb-0">
        <thead>
          <tr>
            <th>نوع الرد</th>
            <th>وقت المعالجة</th>
          </tr>
        </thead>
        <tbody>
          @forelse ($recent_decisions ?? [] as $decision)
          <tr>
            <td class="fw-bold">
              @if($decision->trigger === 'auto_rule') <span class="badge bg-warning text-dark px-2">قاعدة</span>
              @elseif($decision->trigger === 'ai_api') <span class="badge bg-primary px-2">ذكاء RAG</span>
              @else <span class="badge bg-secondary px-2">احتياطي</span> @endif
            </td>
            <td class="text-white-50 fs-7">{{ $decision->response_time_ms }} ms</td>
          </tr>
          @empty
          <tr>
            <td colspan="2" class="text-center py-4 text-white-50">لا توجد سجلات قرارات</td>
          </tr>
          @endforelse
        </tbody>
      </table>
    </div>
  </div>
</div>
@endsection

@section('scripts')
<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
<script>
document.addEventListener('DOMContentLoaded', function () {
    // 0. Monthly Deflection Trends & Agent Hours Saved Chart
    const trendLabels    = @json($monthly_trends['labels'] ?? []);
    const aiResolved     = @json($monthly_trends['ai_resolved_series'] ?? []);
    const hoursSaved     = @json($monthly_trends['hours_saved_series'] ?? []);
    const deflRates      = @json($monthly_trends['deflection_rate_series'] ?? []);
    const revenueAttributed = @json($monthly_trends['revenue_series'] ?? []);

    if (trendLabels.length > 0 && document.querySelector("#deflectionTrendsChart")) {
        const trendOptions = {
            series: [
                {
                    name: 'تذاكر محلولة بالذكاء الاصطناعي',
                    type: 'column',
                    data: aiResolved
                },
                {
                    name: 'ساعات العمل الموفرة (ساعة)',
                    type: 'line',
                    data: hoursSaved
                }
            ],
            chart: {
                height: 280,
                type: 'line',
                toolbar: { show: false },
                background: 'transparent',
                fontFamily: 'var(--font)'
            },
            stroke: { width: [0, 3], curve: 'smooth' },
            colors: ['#22c55e', '#d4af37'],
            plotOptions: {
                bar: {
                    columnWidth: '45%',
                    borderRadius: 4
                }
            },
            fill: {
                opacity: [0.85, 1],
            },
            labels: trendLabels,
            xaxis: {
                categories: trendLabels,
                labels: { style: { colors: '#94a3b8' } },
                axisBorder: { show: false },
                axisTicks: { show: false }
            },
            yaxis: [
                {
                    title: { text: 'تذاكر محلولة', style: { color: '#22c55e' } },
                    labels: { style: { colors: '#94a3b8' } }
                },
                {
                    opposite: true,
                    title: { text: 'ساعات موفرة', style: { color: '#d4af37' } },
                    labels: { style: { colors: '#94a3b8' } }
                }
            ],
            grid: { borderColor: 'rgba(255,255,255,0.05)', strokeDashArray: 4 },
            legend: { position: 'top', horizontalAlign: 'right', labels: { colors: '#fff' } },
            tooltip: {
                shared: true,
                intersect: false,
                theme: 'dark',
                y: {
                    formatter: function (y, { seriesIndex, dataPointIndex }) {
                        if (seriesIndex === 0) return y + ' تذكرة (' + (deflRates[dataPointIndex] || 0) + '% تجنيب)';
                        if (seriesIndex === 1) return y + ' ساعة (~' + (revenueAttributed[dataPointIndex] || 0) + ' ر.س مبيعات)';
                        return y;
                    }
                }
            },
            theme: { mode: 'dark' }
        };
        new ApexCharts(document.querySelector("#deflectionTrendsChart"), trendOptions).render();
    }

    // 1. Messages Chart (Line)
    const labels = @json($chart_labels ?? []);
    const messages = @json($chart_messages ?? []);
    
    if (labels.length > 0) {
        const msgOptions = {
            series: [{ name: 'رسائل', data: messages }],
            chart: {
                type: 'area',
                height: 250,
                toolbar: { show: false },
                background: 'transparent',
                fontFamily: 'var(--font)'
            },
            colors: ['#d4af37'],
            fill: {
                type: 'gradient',
                gradient: { shadeIntensity: 1, opacityFrom: 0.4, opacityTo: 0.05, stops: [0, 100] }
            },
            stroke: { curve: 'smooth', width: 3 },
            xaxis: {
                categories: labels,
                labels: { style: { colors: '#94a3b8' } },
                axisBorder: { show: false },
                axisTicks: { show: false }
            },
            yaxis: { labels: { style: { colors: '#94a3b8' } } },
            grid: { borderColor: 'rgba(255,255,255,0.05)', strokeDashArray: 4 },
            theme: { mode: 'dark' }
        };
        new ApexCharts(document.querySelector("#messagesChart"), msgOptions).render();
    }

    // 2. Channels Donut
    const donutData = @json($channel_donut ?? []);
    const donutLabels = Object.keys(donutData);
    const donutValues = Object.values(donutData);
    
    if (donutLabels.length > 0) {
        const donutOptions = {
            series: donutValues,
            chart: {
                type: 'donut',
                height: 250,
                background: 'transparent',
                fontFamily: 'var(--font)'
            },
            labels: donutLabels.map(l => l.toUpperCase()),
            colors: ['#d4af37', '#10b981', '#0ea5e9', '#f43f5e'],
            stroke: { show: false },
            plotOptions: { pie: { donut: { size: '75%' } } },
            legend: { position: 'bottom', labels: { colors: '#fff' } },
            theme: { mode: 'dark' }
        };
        new ApexCharts(document.querySelector("#channelsChart"), donutOptions).render();
    }
});
</script>
@endsection
